### ISSUE TITLE
problems compiling

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/casarest#1]
originally reported here:

https://github.com/ska-sa/meqtrees-timba/issues/22

Tony writes: I downloaded latest casacore - seems to compile and install OK. I then downloaded casarest 1.3.1 source code gz file, did mkdir build, cd build, cmake .. , but right away I get one of those horrendous bazillion line c++ error messages which seems to come down to

```
[NRC-005592LX 9:29am] [build]> make
[ 1%] Building CXX object components/CMakeFiles/casa_components.dir/SpectralComponents/CompiledSpectralElement.cc.o

blah blah blah

/home/twillis/Downloads/casarest-1.3.1/components/SpectralComponents/CompiledSpectralElement.cc: In member function ‘const casa::String& casa::CompiledSpectralElement::getFunction() const’:
/home/twillis/Downloads/casarest-1.3.1/components/SpectralComponents/CompiledSpectralElement.cc:107:58: error: ‘_getFunction’ was not declared in this scope
CountedPtr > f = _getFunction();
^
/home/twillis/Downloads/casarest-1.3.1/components/SpectralComponents/CompiledSpectralElement.cc:108:50: error: ‘_getFunction’ is not a member of ‘casa::SpectralElement’
return dynamic_cast >(SpectralElement::_getFunction().get())->getText();
^
/home/twillis/Downloads/casarest-1.3.1/components/SpectralComponents/CompiledSpectralElement.cc: In member function ‘virtual void casa::CompiledSpectralElement::_setFunction(const casa::String&)’:
/home/twillis/Downloads/casarest-1.3.1/components/SpectralComponents/CompiledSpectralElement.cc:114:57: error: ‘_getFunction’ was not declared in this scope
CountedPtr > f = _getFunction();
^
/home/twillis/Downloads/casarest-1.3.1/components/SpectralComponents/CompiledSpectralElement.cc:134:2: error: ‘_setFunction’ is not a member of ‘casa::SpectralElement’
SpectralElement::_setFunction(f);
^
make[2]: ** [components/CMakeFiles/casa_components.dir/SpectralComponents/CompiledSpectralElement.cc.o] Error 1
make[1]: *** [components/CMakeFiles/casa_components.dir/all] Error 2
```

**Comment by gijzelaerr** [comment]
which casacore version are you using?

**Comment by twillis449** [comment]
https://github.com/casacore/casacore - downloaded casacore-master.zip 

The build system is 64 bit ubuntu 14.04

**Comment by gijzelaerr** [comment]
can you try the latest *release*, not the master

https://github.com/casacore/casacore/releases

**Comment by twillis449** [comment]
Hi - looks like this must be my bad.  :( 

I did a recursive search down from /usr on my machine and found some *casa* files that I was not aware of - including a whole set of libcasa* files under /usr/local/miriad/linux64/casacore 

Getting rid of all this stuff plus doing another build of casacore-master now seems to have casarest 1.3.1 building OK. :)

I'll now try the latest meqtrees-timba.

**Comment by gijzelaerr** [comment]
ok, already thought something like that.
