### ISSUE TITLE
compile fails with "no match for call to ‘(casa::Quantum<double>)"

### ISSUE THREAD

**Issue by nzasch** [casacore/casarest#25]
Hi
compiling casarest master against casacore 2.4.1 with gcc 7.3.1 on CentOS7 fails with the folowing error:

no match for call to ‘(casa::Quantum<double>)

entire cmake & make output in attachment

[casarest_error.txt](https://github.com/casacore/casarest/files/2712200/casarest_error.txt)

casacore compilation in the same environment with flags "-DBUILD_PYTHON=True -DUSE_OPENMP=True -DUSE_FFTW3=True -DUSE_HDF5=True" went well 

many thanks
Francesco

**Comment by gijzelaerr** [comment]
The current master only supports caaacore 3.0

Op do 27 dec. 2018 12:42 schreef nzasch <notifications@github.com:

**Comment by gijzelaerr** [comment]
i'll update the readme to explain

**Comment by nzasch** [comment]
ok, thank you

**Comment by gijzelaerr** [comment]
updated readme.
