### ISSUE TITLE
The OrderedMap and SimpleOrderedMap are now deprecated in casacore

### ISSUE THREAD

**Issue by steve-ord** [casacore/casarest#26]
I'm having trouble building against casacore3.1 as the msvis component is using deprecated casacore classes. I don't want to force my users to use these as they do not need msvis. Is it possible to make some optional build targets. I could put together some edits to the cmake and submit a pull request?

**Comment by gijzelaerr** [comment]
hi @steve-ord , that would be great. Maybe autodetect against which casacore you are compiling?

**Comment by gervandiepen** [comment]
I've informed Malte about this change.
It's already possible to specify -DBUILD_DEPRECATED=ON at cmake.

**Comment by gervandiepen** [comment]
Note that CASA has already changed all its code for this purpose. Do you
use an old msvis?

**Comment by tammojan** [comment]
This is casarest, so a fork from an old casa.

**Comment by steve-ord** [comment]
I've tried the -DBUILD_DEPRECATED=ON and it is not sufficient - the files are now included in the build but the build stage of casarest/msvis still fails. I'll put together some more information today.

**Comment by steve-ord** [comment]
For example: 
If I build casacore with  -DBUILD_DEPRECATED=ON then try to build casarest/msvis I still get the deprecated error.

Hmm maybe I just need to set AIPS_USE_DEPRECATED in the casarest build .... hang on.

**Comment by gervandiepen** [comment]
I've created casarest branch useSTL in which all old casacore classes such
as Map have been replaced by their STL counterparts.
Could you please try it out before we do the merge?

**Comment by tammojan** [comment]
This should be fixed in the current master. I'll release a new version as well.
