### ISSUE TITLE
License/Copying file

### ISSUE THREAD

**Issue by badshah400** [casacore/casarest#38]
I am trying to package casarest for openSUSE (as a separate package from casacore); however, one issue is the lack of a License/Copying file specific to casarest, which would prevent my packages from getting into the official distro. Could you please clarify the licensing situation and perhaps add a LICENSE/COPYING file similar to the one casacore has?

Thanks.

**Comment by tammojan** [comment]
Sorry that took a while. Please note that casarest is not actively being maintained.
